# ```fastf1``` Tutorial #

### Instalation ###
```fastf1``` can be installed via ```pip3 install fastf1```.

### Documentation ###
- ```fastf1``` Documentation - [Link](https://docs.fastf1.dev/);
- ```fastf1``` Reference - [Link](https://theoehrly-fast-f1.mintlify.app/api/events);

### Importing Dependencies ###

In [ ]:
import fastf1
import pandas as pd
from datetime import datetime

### Core Concepts ###
```fastf1``` organizes Formula 1 data around an ```event``` and one of its ```sessions```. The usual path is: 
1. Choose a ```schedule``` (based on an year);
2. Get an ```Event``` (a race weekends);
3. Get a ```Session``` (individual practice, qualifying, or race sessions);
4. Load the data and navigate ```laps```, ```results```, telemetry, messages, weather, and circuit information;

The public namespaces include ```fastf1.core```, ```fastf1.events```, ```fastf1.ergast```, ```fastf1.livetiming```, ```fastf1.plotting```, ```fastf1.utils```, and ```fastf1.legacy```. 

```fastf1.Cache``` controls local HTTP/data caching and should b enabled once at process startup (should be treated as infrastructure, not as a per-request convenience, that improves iteration speed and reduces unnecessary traffic).

**Limits**<br>
Loading remote data may fail because of connectivity, rate limits, upstream availability, or an unsupported session. 

### Data Sources ###
There're 3 main data sources:
- ```fastf1```: API's own backend (supports from 2018 on; default);
- ```f1timing```: data from the *F1 Live Timing* API (supports from 2018 on; sessions with no timing data are not listed);
- ```ergast```: data from Ergast (supports from 1950 on; no local times available);

### ```Events``` ###
An ```event``` summarizes a racing weekend.

**Event Schedules**<br>
```fastf1.events.EventSchedule``` is a season-level table of ```events```, and a ```fastf1.events.Event``` represents one ```event``` record (with individual ```sessions``` within it).

In [ ]:
# 'get_event_schedule()': gets events schedule for specific season
schedule1 = fastf1.get_event_schedule(year= 2025, # 'year': championship year
                                     include_testing= True, # 'include_testing': whether to include testing sessions
                                     backend= None) # 'backend': specific backend data source
                                                    # (Available: 'fastf1', 'f1timing', 'ergast') 
print(f"Columns: {', '.join(schedule.columns)}")
schedule1.head(3)

Columns: RoundNumber, Country, Location, OfficialEventName, EventDate, EventName, EventFormat, Session1, Session1Date, Session1DateUtc, Session2, Session2Date, Session2DateUtc, Session3, Session3Date, Session3DateUtc, Session4, Session4Date, Session4DateUtc, Session5, Session5Date, Session5DateUtc, F1ApiSupport

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2025,2025-02-28,Pre-Season Testing,testing,Practice 1,2025-02-26 10:00:00+03:00,2025-02-26 07:00:00,...,Practice 3,2025-02-28 10:00:00+03:00,2025-02-28 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,1,Australia,Melbourne,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,Australian Grand Prix,conventional,Practice 1,2025-03-14 12:30:00+11:00,2025-03-14 01:30:00,...,Practice 3,2025-03-15 12:30:00+11:00,2025-03-15 01:30:00,Qualifying,2025-03-15 16:00:00+11:00,2025-03-15 05:00:00,Race,2025-03-16 15:00:00+11:00,2025-03-16 04:00:00,True
2,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2025,2025-03-23,Chinese Grand Prix,sprint_qualifying,Practice 1,2025-03-21 11:30:00+08:00,2025-03-21 03:30:00,...,Sprint,2025-03-22 11:00:00+08:00,2025-03-22 03:00:00,Qualifying,2025-03-22 15:00:00+08:00,2025-03-22 07:00:00,Race,2025-03-23 15:00:00+08:00,2025-03-23 07:00:00,True

In [ ]:
# 'get_events_remaining()': gets schedule for remaining events in the season
schedule2 = fastf1.get_events_remaining(dt= datetime(2025, 11, 1), # 'dt': DateTime to get events after
                                    include_testing= True, # 'include_testing': whether to include testing sessions
                                    backend= None) # 'backend': specific backend data source
schedule2

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
21,21,Brazil,São Paulo,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,2025-11-09,São Paulo Grand Prix,sprint_qualifying,Practice 1,2025-11-07 11:30:00-03:00,2025-11-07 14:30:00,...,Sprint,2025-11-08 11:00:00-03:00,2025-11-08 14:00:00,Qualifying,2025-11-08 15:00:00-03:00,2025-11-08 18:00:00,Race,2025-11-09 14:00:00-03:00,2025-11-09 17:00:00,True
22,22,United States,Las Vegas,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2025,2025-11-22,Las Vegas Grand Prix,conventional,Practice 1,2025-11-20 16:30:00-08:00,2025-11-21 00:30:00,...,Practice 3,2025-11-21 16:30:00-08:00,2025-11-22 00:30:00,Qualifying,2025-11-21 20:00:00-08:00,2025-11-22 04:00:00,Race,2025-11-22 20:00:00-08:00,2025-11-23 04:00:00,True
23,23,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2025,2025-11-30,Qatar Grand Prix,sprint_qualifying,Practice 1,2025-11-28 16:30:00+03:00,2025-11-28 13:30:00,...,Sprint,2025-11-29 17:00:00+03:00,2025-11-29 14:00:00,Qualifying,2025-11-29 21:00:00+03:00,2025-11-29 18:00:00,Race,2025-11-30 19:00:00+03:00,2025-11-30 16:00:00,True
24,24,United Arab Emirates,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2025-12-07,Abu Dhabi Grand Prix,conventional,Practice 1,2025-12-05 13:30:00+04:00,2025-12-05 09:30:00,...,Practice 3,2025-12-06 14:30:00+04:00,2025-12-06 10:30:00,Qualifying,2025-12-06 18:00:00+04:00,2025-12-06 14:00:00,Race,2025-12-07 17:00:00+04:00,2025-12-07 13:00:00,True

In [32]:
# 'is_testing()': returns bool for whether a specific event is a testing event
schedule2.is_testing()

21    False
22    False
23    False
24    False
Name: EventFormat, dtype: bool

**Event**<br>
Represents a single race weekend or testing event. Each ```event``` contains:
- ```RoundNumber```: round number;
- ```Country```: country where ```event``` takes place;
- ```Location```: circuit name;
- ```EventName```: ```event``` short name;
- ```OfficialEventName```: ```event``` full name
- ```EventDate```: ```event``` date (usually race day);
- ```EventFormat```: format type (```conventional```, ```sprint```, ```sprint_shootout```, ```sprint_qualifying```, ```testing```);
- ```Session[X]```: each session name;
- ```Session[X]Date```: each session local timestamp;
- ```Session[X]DateUtc```: each ssession UTC timestamp;
- ```F1ApiSupport```: whether API data is available;

In [38]:
# 'get_event_by_round()': gets event by its round number
event = schedule1.get_event_by_round(round= 1) # 'round': round number) 
event[["EventDate", "EventName","Session1", "Session2", "Session3", "Session4", "Session5"]]

EventDate      2025-03-16 00:00:00
EventName    Australian Grand Prix
Session1                Practice 1
Session2                Practice 2
Session3                Practice 3
Session4                Qualifying
Session5                      Race
dtype: object

In [56]:
# 'get_event_by_name()': gets event by its name (with fuzzy matching)
event = schedule1.get_event_by_name(name= "Monaco") # 'name': event name 
event[["EventDate", "EventName","Session1", "Session2", "Session3", "Session4", "Session5"]]

EventDate    2025-05-25 00:00:00
EventName      Monaco Grand Prix
Session1              Practice 1
Session2              Practice 2
Session3              Practice 3
Session4              Qualifying
Session5                    Race
dtype: object

In [58]:
# 'get_event()': gets events for specific season and name
event = fastf1.get_event(year= 2025, # 'year': championship year
                         gp= "Brazil", # 'gp': event name 
                         backend= None, # 'backend': specific backend data source
                         exact_match= False) # 'exact_match': whether match query str precisely
event[["EventDate", "EventName","Session1", "Session2", "Session3", "Session4", "Session5"]]

EventDate     2025-11-09 00:00:00
EventName    São Paulo Grand Prix
Session1               Practice 1
Session2        Sprint Qualifying
Session3                   Sprint
Session4               Qualifying
Session5                     Race
dtype: object

In [59]:
# 'is_testing()': returns True if event is a testing one
event.is_testing() # 2025 Monaco

False

**Session**<br>
Represents one of the many sessions within an ```event```. Each ```session``` is defined by:
- ```event```: associated event;
- ```session_name```: session name (```Qualifying```, ```Race```, ```FP1```);

Each ```session``` contains:
- ```event```: associated event;
- ```name```: session name;
- ```date```: session timestamp;
​- ```drivers```: list of all driver numbers that participated in session;
- ```results```: session results with driver information;
- ```laps```: all laps from all drivers in session;
- ```car_data```: dictionary of car telemetry (speed, RPM, etc) keyed by driver number (each value is a ```Telemetry``` object);
- ```pos_data```: dictionary of car position data (X, Y, Z coordinates) keyed by driver number (each value is a ```Telemetry``` object);
​- ```weather_data```: DataFrame containing weather data for session;
- ```session_status```: session status data (```Started```, ```Finished```, ```Aborted```);
- ```track_status```: track status data (yellow flags, red flags, etc);
- ```race_control_messages```: race control messages for session;
- ```session_info```: session information including meeting, session, country and circuit names and uuids;
- ```total_laps```: originally scheduled number of laps for race-like sessions;
- ```t0_date```: timestamp marking the beginning of data stream (when session time is zero);
- ```session_start_time```: session time at which the session was started;

In [80]:
# 'get_session()': gets event by its name (with fuzzy matching)
session = fastf1.get_session(year= 2025, # 'year': championship year
                             gp= "Monaco", # 'name': event name or round number (with fuzzy matching)
                             identifier= 5, # 'identifier': session name or number (1-5)
                             backend= None) # 'backend': specific backend data source
session

2025 Season Round 8: Monaco Grand Prix - Race

In [61]:
# 'get_session_name()': returns full session name of specific session from event
event.get_session_name(identifier= 1) # 'identifier': session name or number (1-5)

'Practice 1'

In [62]:
# 'get_session_date()': returns date/time for specific session
event.get_session_date(identifier= 1, # 'identifier': session name or number (1-5)
                       utc= True) # 'utc': whether to return in UTC

Timestamp('2025-11-07 14:30:00')

In [63]:
# 'get_practice()': returns practice session for event
event.get_practice(number= 1) # 'number': practice session number (1-3)

2025 Season Round 21: São Paulo Grand Prix - Practice 1

In [64]:
# 'get_qualifying()': returns qualifying session for event
event.get_qualifying()

2025 Season Round 21: São Paulo Grand Prix - Qualifying

In [65]:
# 'get_sprint()': returns sprint session for event
event.get_sprint()

2025 Season Round 21: São Paulo Grand Prix - Sprint

In [66]:
# 'get_race()': returns race session for event
event.get_race()

2025 Season Round 21: São Paulo Grand Prix - Race

In [ ]:
# 'load()': loads session data
session.load(laps= True, # 'laps': whether to load laps data
             telemetry= True, # 'telemetry': whether to load telemetry data
             weather= True, # 'weather': whether to load weather data
             messages= True) # 'messages': whether to load messages data

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']

In [117]:
# Accessing session's results
session.results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:40:33.843000,Finished,25.0,78.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:03.131000,Finished,18.0,78.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,3.0,3,3.0,NaT,NaT,NaT,0 days 00:00:03.658000,Finished,15.0,78.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:20.572000,Finished,12.0,78.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:51.387000,Finished,10.0,78.0

In [88]:
# Accessing session's start time
session.session_start_time

datetime.timedelta(seconds=3368, microseconds=809000)

In [147]:
# Accessing session's status
session.session_status

                    Time     Status
0 0 days 00:00:06.127000   Inactive
1 0 days 00:56:08.809000    Started
2 0 days 02:36:42.884000   Finished
3 0 days 02:39:20.014000  Finalised
4 0 days 02:39:20.014000       Ends

In [149]:
# Accessing session's race control messages
session.race_control_messages.head(3)

,Time,Category,Message,Status,Flag,Scope,Sector,RacingNumber,Lap
0,2025-05-25 12:20:01,Flag,GREEN LIGHT - PIT EXIT OPEN,None,GREEN,Track,NaN,None,1
1,2025-05-25 12:30:01,Other,PIT EXIT CLOSED,None,None,None,NaN,None,1
2,2025-05-25 12:31:26,Flag,DOUBLE YELLOW IN TRACK SECTOR 7,None,DOUBLE YELLOW,Sector,7.0,None,1

**Driver**<br>

In [ ]:
# 'get_driver()': gets driver object
driver = session.get_driver(identifier= 'VER') # 'identifier': driver 3 letter identifier or number (1-99)
                                               # Returns 'DriverResult' object
driver

DriverNumber                                                          1
BroadcastName                                              M VERSTAPPEN
Abbreviation                                                        VER
DriverId                                                 max_verstappen
TeamName                                                Red Bull Racing
TeamColor                                                        4781D7
TeamId                                                         red_bull
FirstName                                                           Max
LastName                                                     Verstappen
FullName                                                 Max Verstappen
HeadshotUrl           https://media.formula1.com/d_driver_fallback_i...
CountryCode
Position                                                            NaN
ClassifiedPosition
GridPosition                                                        NaN
Q1                                                                  NaT
Q2                                                                  NaT
Q3                                                                  NaT
Time                                                                NaT
Status
Points                                                              NaN
Laps                                                                NaN
Name: 1, dtype: object

In [ ]:
# Accessing drivers numbers
session.drivers[:3] # First 3 drivers

['4', '16', '81']

**Circuit/Track**<br>

In [151]:
# 'get_circuit_info()': gets circuit information
circuit = session.get_circuit_info() # Returns 'CircuitInfo' object
circuit.corners.head() # Available:
                       #    'corners': 'Number', 'Letter', 'X', 'Y', 'Distance'
                       #    'marshal_lights': locations of marshal light panels around track
                       #    'marshal_sectors': marshal sector locations
                       #    'rotation': rotation angle (degrees) required to align the track map

             X            Y  Number Letter       Angle     Distance
0 -7381.106934 -4719.949219       1         140.384631   186.471184
1 -3634.549072 -3769.346436       2         103.015117   581.687735
2 -2275.649414 -3071.900879       3         168.949842   744.149504
3 -2745.113281 -1956.109497       4        -174.396257   873.202140
4 -1422.224854  -197.893692       5          76.191057  1102.762534

In [152]:
# Accessing session's track status
session.track_status.head()

                    Time Status   Message
0        0 days 00:00:00      1  AllClear
1 0 days 00:24:26.032000      2    Yellow
2 0 days 00:24:35.108000      1  AllClear
3 0 days 00:57:00.403000      2    Yellow
4 0 days 00:57:18.050000      1  AllClear

**Laps**<br>
```Laps``` class provides multiple laps timing data and telemetry. Each ```Laps``` contains:
- ```Time```: lap completion time;
- ```Driver```: driver 3-letter abbreviation;
- ```DriverNumber```: driver number;
- ```LapTime```: lap time duration
- ```LapNumber```: lap number;
- ```Stint```: stint number;
- ```PitOutTime```: time when car exited pit lane;
- ```PitInTime```: time when car entered pit lane;
- ```Sector[X]Time```: sector [X] time (1-3);
- ```Sector[X]SessionTime```: session time at sector [X] (1-3);
- ```SpeedI[X]```: speed trap at intermediate [X] (km/h; 1-2);
- ```SpeedFL```: speed trap at finish line (km/h);
- ```SpeedST```: speed trap at speed trap (km/h);
- ```IsPersonalBest```: whether lap is driver’s personal best;
- ```Compound```: tyre compound (```SOFT```, ```MEDIUM```, ```HARD```, ```INTERMEDIATE```, ```WET```);
- ```TyreLife```: laps completed on current set of tyres;
- ```FreshTyre```: whether tyres were new;
- ```Team```: team name;
- ```LapStartTime```: time when the lap started;
- ```LapStartDate```: date when the lap started;
- ```TrackStatus```: track status flags during the lap;
- ```Position```: position at end of lap;
- ```Deleted```: whether lap time was deleted;
- ```DeletedReason```: reason for deletion;
- ```FastF1Generated```: whether lap was generated by *FastF1*;
- ```IsAccurate```: whether lap passed accuracy validation;

In [ ]:
# Accessing total number of laps (race/sprint only)
session.total_laps

78

In [127]:
# Accessing all laps
session.laps.head(3)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:36.090000,VER,1,0 days 00:01:27.020000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:38.394000,...,True,Red Bull Racing,0 days 00:56:08.809000,2025-05-25 13:03:09.195,12,4.0,False,,False,False
1,0 days 00:59:22.408000,VER,1,0 days 00:01:46.318000,2.0,1.0,NaT,NaT,0 days 00:00:34.949000,0 days 00:00:45.145000,...,True,Red Bull Racing,0 days 00:57:36.090000,2025-05-25 13:04:36.476,16,4.0,False,,False,False
2,0 days 01:01:11.223000,VER,1,0 days 00:01:48.815000,3.0,1.0,NaT,NaT,0 days 00:00:32.110000,0 days 00:00:47.430000,...,True,Red Bull Racing,0 days 00:59:22.408000,2025-05-25 13:06:22.794,6,4.0,False,,False,False

In [95]:
# Accessing Verstappen's laps
session.laps.pick_drivers("VER").head(2) # First 2 laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:36.090000,VER,1,0 days 00:01:27.020000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:38.394000,...,True,Red Bull Racing,0 days 00:56:08.809000,2025-05-25 13:03:09.195,12,4.0,False,,False,False
1,0 days 00:59:22.408000,VER,1,0 days 00:01:46.318000,2.0,1.0,NaT,NaT,0 days 00:00:34.949000,0 days 00:00:45.145000,...,True,Red Bull Racing,0 days 00:57:36.090000,2025-05-25 13:04:36.476,16,4.0,False,,False,False

In [96]:
# Accessing Verstappen's laps 1, 3, 5
session.laps.pick_drivers("VER").pick_laps([1,3,5])

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:36.090000,VER,1,0 days 00:01:27.020000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:38.394000,...,True,Red Bull Racing,0 days 00:56:08.809000,2025-05-25 13:03:09.195,12,4.0,False,,False,False
2,0 days 01:01:11.223000,VER,1,0 days 00:01:48.815000,3.0,1.0,NaT,NaT,0 days 00:00:32.110000,0 days 00:00:47.430000,...,True,Red Bull Racing,0 days 00:59:22.408000,2025-05-25 13:06:22.794,6,4.0,False,,False,False
4,0 days 01:04:12.313000,VER,1,0 days 00:01:20.800000,5.0,1.0,NaT,NaT,0 days 00:00:21.744000,0 days 00:00:37.485000,...,True,Red Bull Racing,0 days 01:02:51.513000,2025-05-25 13:09:51.899,1,4.0,False,,False,True

In [140]:
# Accessing Verstappen's fastest lap
lap = session.laps.pick_drivers("VER").pick_fastest()
lap

Time                      0 days 01:55:10.368000
Driver                                       VER
DriverNumber                                   1
LapTime                   0 days 00:01:14.230000
LapNumber                                   45.0
Stint                                        2.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:19.363000
Sector2Time               0 days 00:00:35.111000
Sector3Time               0 days 00:00:19.756000
Sector1SessionTime        0 days 01:54:15.536000
Sector2SessionTime        0 days 01:54:50.647000
Sector3SessionTime        0 days 01:55:10.403000
SpeedI1                                    207.0
SpeedI2                                    199.0
SpeedFL                                    260.0
SpeedST                                    280.0
IsPersonalBest                              True
Compound                                  MEDIUM
TyreLife                                    17.0
FreshTyre                                   True
Team                             Red Bull Racing
LapStartTime              0 days 01:53:56.138000
LapStartDate          2025-05-25 14:00:56.524000
TrackStatus                                    1
Position                                     4.0
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 44, dtype: object

In [137]:
# Accessing qualifying quick laps (within 107% of fastest)
session.laps.pick_quicklaps().head(3)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
7,0 days 01:08:09.006000,VER,1,0 days 00:01:17.714000,8.0,1.0,NaT,NaT,0 days 00:00:20.467000,0 days 00:00:36.796000,...,True,Red Bull Racing,0 days 01:06:51.292000,2025-05-25 13:13:51.678,12,4.0,False,,False,True
10,0 days 01:12:06.861000,VER,1,0 days 00:01:17.481000,11.0,1.0,NaT,NaT,0 days 00:00:20.295000,0 days 00:00:36.676000,...,True,Red Bull Racing,0 days 01:10:49.380000,2025-05-25 13:17:49.766,21,4.0,False,,False,True
11,0 days 01:13:24.989000,VER,1,0 days 00:01:18.128000,12.0,1.0,NaT,NaT,0 days 00:00:20.612000,0 days 00:00:37.001000,...,True,Red Bull Racing,0 days 01:12:06.861000,2025-05-25 13:19:07.247,1,4.0,False,,False,True

In [135]:
# Accessing Red Bull's laps
session.laps.pick_teams("Red Bull Racing").pick_laps([1])

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:36.090000,VER,1,0 days 00:01:27.020000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:38.394000,...,True,Red Bull Racing,0 days 00:56:08.809000,2025-05-25 13:03:09.195,12,4.0,False,,False,False
352,0 days 00:57:59.546000,TSU,22,0 days 00:01:50.476000,1.0,1.0,NaT,0 days 00:57:35.742000,NaT,0 days 00:00:40.335000,...,True,Red Bull Racing,0 days 00:56:08.809000,2025-05-25 13:03:09.195,126,17.0,False,,False,False

**Lap**<br>
```Lap``` class represents a single lap (```Laps``` is an aggregate of ```Lap```).

In [142]:
# Getting single lap's full telemetry
lap.get_telemetry().head(3)

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
2,2025-05-25 14:00:56.524,0 days 01:53:56.138000,,130.018056,0 days 00:00:00,11564.679931,264.790001,6,100.0,False,0,interpolation,0.093319,0.000029,OnTrack,-7662.872842,-6590.298846,502.059263
3,2025-05-25 14:00:56.545,0 days 01:53:56.159000,,130.018056,0 days 00:00:00.021000,11542.000000,265.000000,6,100.0,False,0,car,1.645278,0.000503,OnTrack,-7665.071820,-6555.732496,502.207353
4,2025-05-25 14:00:56.717,0 days 01:53:56.331000,,130.018056,0 days 00:00:00.193000,11072.225000,266.612500,6,100.0,False,0,pos,14.410683,0.004404,OnTrack,-7678.000000,-6352.000000,503.000000

In [143]:
# Getting single lap's car data
lap.get_car_data().head(3)

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2025-05-25 14:00:56.545,11542.0,265.0,6,100.0,False,0,car,0 days 00:00:00.021000,0 days 01:53:56.159000
1,2025-05-25 14:00:56.865,10668.0,268.0,6,100.0,False,0,car,0 days 00:00:00.341000,0 days 01:53:56.479000
2,2025-05-25 14:00:57.065,10754.0,271.0,7,100.0,False,0,car,0 days 00:00:00.541000,0 days 01:53:56.679000

In [144]:
# Getting single lap's position data
lap.get_pos_data().head(3)

,Date,Status,X,Y,Z,Source,Time,SessionTime
0,2025-05-25 14:00:56.717,OnTrack,-7678.0,-6352.0,503.0,pos,0 days 00:00:00.193000,0 days 01:53:56.331000
1,2025-05-25 14:00:56.997,OnTrack,-7681.0,-6247.0,503.0,pos,0 days 00:00:00.473000,0 days 01:53:56.611000
2,2025-05-25 14:00:57.237,OnTrack,-7673.0,-6066.0,503.0,pos,0 days 00:00:00.713000,0 days 01:53:56.851000

**Telemetry**<br>
```Telemetry``` contains multiple data channels:
- ```Car```
    - ```Speed```: car speed in km/h;
    - ```RPM```: engine RPMs;
    - ```nGear```: current gear number (1-8);
    - ```Throttle```: throttle pedal position (0-100%);
    - ```Brake```: whether brakes are applied (bool);
    - ```DRS```: DRS (Drag Reduction System) status (```0```: not available, ```1```: available but not activated, ```2```: available and activated, ```3```: active with different detection);
- ```Position```
    - ```X```: X coordinate position in 1/10 meters;
    - ```Y```: Y coordinate position in 1/10 meters;
    - ```Z```: Z coordinate position in 1/10 meters;
    - ```Status```: position status (```OnTrack```, ```OffTrack```);
- ```Timing```
    - ```Time```: relative time to start of the data slice (0: first sample);
    - ```SessionTime```: time elapsed since start of session;
    - ```Date```: date/time the sample was created;
    - ```Source```: how sample was created (```car```: original car sample, ```pos```: original position sample, ```interpolated```: artificially created/interpolated sample);
- ```Computed```
    - ```Distance```: distance driven since first sample (meters);
    - ```RelativeDistance```: relative distance from 0 (first sample) to 1 (last sample);
    - ```DifferentialDistance```: distance driven between consecutive samples (meters);
    - ```DriverAhead```: driver number of car ahead;
    - ```DistanceToDriverAhead```: distance to the car ahead (meters);

In [109]:
# Accessing Verstappen's fastest lap telemetry (samples)
session.laps.pick_drivers("VER").pick_fastest().get_telemetry().head(3)

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
2,2025-05-25 14:00:56.524,0 days 01:53:56.138000,,130.018056,0 days 00:00:00,11564.679931,264.790001,6,100.0,False,0,interpolation,0.093319,0.000029,OnTrack,-7662.872842,-6590.298846,502.059263
3,2025-05-25 14:00:56.545,0 days 01:53:56.159000,,130.018056,0 days 00:00:00.021000,11542.000000,265.000000,6,100.0,False,0,car,1.645278,0.000503,OnTrack,-7665.071820,-6555.732496,502.207353
4,2025-05-25 14:00:56.717,0 days 01:53:56.331000,,130.018056,0 days 00:00:00.193000,11072.225000,266.612500,6,100.0,False,0,pos,14.410683,0.004404,OnTrack,-7678.000000,-6352.000000,503.000000

In [108]:
# Accessing data by driver number
session.car_data["1"].head(3) # Verstappen

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2025-05-25 12:09:09.644,0.0,0.0,0,0.0,False,0,car,0 days 00:02:09.258000,0 days 00:02:09.258000
1,2025-05-25 12:09:09.963,0.0,0.0,0,0.0,False,0,car,0 days 00:02:09.577000,0 days 00:02:09.577000
2,2025-05-25 12:09:10.243,0.0,0.0,0,0.0,False,0,car,0 days 00:02:09.857000,0 days 00:02:09.857000

In [107]:
# Slicing by lap
session.car_data["1"].slice_by_lap(ref_laps= session.laps.pick_drivers("VER").pick_laps([1,3,5]), # 'ref_laps': laps to slice by (must be 'Laps' object)
                                   pad= 0, # 'pad': number of samples to pad the slice with
                                   pad_side= "both", # 'pad_side': where to add padding ('both', 'before', 'after')
                                   interpolate_edges= False).head(3) # 'interpolate_edges': whether to interpolate the edges

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
12028,2025-05-25 13:03:09.252,10005.0,0.0,1,17.0,True,1,car,0 days 00:00:00.057000,0 days 00:56:08.866000
12029,2025-05-25 13:03:09.612,9406.0,0.0,1,17.0,True,1,car,0 days 00:00:00.417000,0 days 00:56:09.226000
12030,2025-05-25 13:03:09.772,8286.0,0.0,1,17.0,False,1,car,0 days 00:00:00.577000,0 days 00:56:09.386000

In [116]:
# Slicing by Time
session.car_data["1"].slice_by_time(start_time= pd.to_timedelta(10, unit= "m") , # 'start_time': minutes from session start 
                                    end_time= pd.to_timedelta(15, unit= "m") , # 'end_time': minutes from session end
                                    pad= 0, # 'pad': number of samples to pad the slice with
                                    pad_side= "both", # 'pad_side': where to add padding ('both', 'before', 'after')
                                    interpolate_edges= False).head(3) # 'interpolate_edges': whether to interpolate the edges

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
1762,2025-05-25 12:17:00.403,0.0,0.0,0,0.0,False,1,car,0 days 00:00:00.017000,0 days 00:10:00.017000
1763,2025-05-25 12:17:00.563,0.0,0.0,0,0.0,False,1,car,0 days 00:00:00.177000,0 days 00:10:00.177000
1764,2025-05-25 12:17:00.803,0.0,0.0,0,0.0,False,1,car,0 days 00:00:00.417000,0 days 00:10:00.417000

---